// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = 100,
                            DepartmentId = 1,
                            MinDegree = 50,
                            Name = "Introduction to Programming"
                        },
                        new
                        {
                            Id = 2,
                            Degree = 100,
                            DepartmentId = 1,
                            MinDegree = 60,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 3,
                            Degree = 100,
                            DepartmentId = 2,
                            MinDegree = 55,
                            Name = "Object-Oriented Design"
                        },
                        new
                        {
                            Id = 4,
                            Degree = 100,
                            DepartmentId = 3,
                            MinDegree = 65,
                            Name = "Machine Learning Fundamentals"
                        },
                        new
                        {
                            Id = 5,
                            Degree = 100,
                            DepartmentId = 4,
                            MinDegree = 60,
                            Name = "Network Security"
                        });
                });

            modelBuilder.Entity("Project.Models.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Degree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CourseResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Degree = 90m,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Degree = 78m,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Degree = 82m,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Degree = 95m,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Degree = 88m,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            Degree = 70m,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            Degree = 55m,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            Degree = 72m,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 5,
                            Degree = 62m,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 5,
                            Degree = 80m,
                            TraineeId = 6
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 5,
                            Degree = 58m,
                            TraineeId = 7
                        });
                });

            modelBuilder.Entity("Project.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            ManagerName = "Dr. Ahmed Hassan",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            ManagerName = "Dr. Mona Khalil",
                            Name = "Information Systems"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            ManagerName = "Dr. Youssef Adel",
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            ManagerName = "Dr. Sara Ibrahim",
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            ManagerName = "Dr. Khaled Mostafa",
                            Name = "Cybersecurity"
                        });
                });

            modelBuilder.Entity("Project.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Nasr City",
                            CourseId = 1,
                            DepartmentId = 1,
                            Email = "ahmed.hassan@uni.edu",
                            ImageUrl = "/Images/male_avatar.jpeg",
                            Name = "Dr. Ahmed Hassan",
                            Phone = "01001234567",
                            Salary = 15000.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cairo, Heliopolis",
                            CourseId = 1,
                            DepartmentId = 1,
                            Email = "hala.sami@uni.edu",
                            ImageUrl = "/Images/female.jpeg",
                            Name = "Dr. Hala Sami",
                            Phone = "01002234567",
                            Salary = 14500.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza, Haram",
                            CourseId = 1,
                            DepartmentId = 1,
                            Email = "tarek.fouad@uni.edu",
                            ImageUrl = "/Images/male_avatar.jpeg",
                            Name = "Dr. Tarek Fouad",
                            Phone = "01103234567",
                            Salary = 14800.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Giza, Dokki",
                            CourseId = 2,
                            DepartmentId = 1,
                            Email = "mona.khalil@uni.edu",
                            ImageUrl = "/Images/female.jpeg",
                            Name = "Dr. Mona Khalil",
                            Phone = "01102345678",
                            Salary = 16000.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cairo, Maadi",
                            CourseId = 2,
                            DepartmentId = 1,
                            Email = "rania.wagdy@uni.edu",
                            ImageUrl = "/Images/female.jpeg",
                            Name = "Dr. Rania Wagdy",
                            Phone = "01004567890",
                            Salary = 15200.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "Alexandria, Smouha",
                            CourseId = 3,
                            DepartmentId = 2,
                            Email = "youssef.adel@uni.edu",
                            ImageUrl = "/Images/male_avatar.jpeg",
                            Name = "Dr. Youssef Adel",
                            Phone = "01203456789",
                            Salary = 15500.0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cairo, Maadi",
                            CourseId = 4,
                            DepartmentId = 3,
                            Email = "sara.ibrahim@uni.edu",
                            ImageUrl = "/Images/female.jpeg",
                            Name = "Dr. Sara Ibrahim",
                            Phone = "01005567890",
                            Salary = 17500.0
                        },
                        new
                        {
                            Id = 8,
                            Address = "Cairo, Heliopolis",
                            CourseId = 5,
                            DepartmentId = 4,
                            Email = "khaled.mostafa@uni.edu",
                            ImageUrl = "/Images/male_avatar.jpeg",
                            Name = "Dr. Khaled Mostafa",
                            Phone = "01105678901",
                            Salary = 16500.0
                        });
                });

            modelBuilder.Entity("Project.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Grade = 88.5m,
                            ImageUrl = "/Images/male_trainee.jpeg",
                            Name = "Ali Mahmoud",
                            PhoneNumber = "01011111111"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Grade = 92.0m,
                            ImageUrl = "/Images/female_trainee.jpeg",
                            Name = "Salma Nabil",
                            PhoneNumber = "01112222222"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Grade = 79.5m,
                            ImageUrl = "/Images/male_trainee.jpeg",
                            Name = "Omar Tarek",
                            PhoneNumber = "01213333333"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Grade = 85.0m,
                            ImageUrl = "/Images/male_trainee.jpeg",
                            Name = "Nour Adel",
                            PhoneNumber = "01014444444"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Grade = 74.0m,
                            ImageUrl = "/Images/male_trainee.jpeg",
                            Name = "Yousef Samir",
                            PhoneNumber = "01115555555"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 4,
                            Grade = 90.0m,
                            ImageUrl = "/Images/female_trainee.jpeg",
                            Name = "Hana Wael",
                            PhoneNumber = "01216666666"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 5,
                            Grade = 68.0m,
                            ImageUrl = "/Images/male_trainee.jpeg",
                            Name = "Karim Hossam",
                            PhoneNumber = "01017777777"
                        });
                });

            modelBuilder.Entity("Project.Models.Course", b =>
                {
                    b.HasOne("Project.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project.Models.CourseResult", b =>
                {
                    b.HasOne("Project.Models.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Trainee", "Trainee")
                        .WithMany("CourseResults")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Project.Models.Instructor", b =>
                {
                    b.HasOne("Project.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project.Models.Trainee", b =>
                {
                    b.HasOne("Project.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project.Models.Course", b =>
                {
                    b.Navigation("CourseResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Project.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("Project.Models.Trainee", b =>
                {
                    b.Navigation("CourseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
